=== cicerorfonseca/js-xml-xsd/flights.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="flights">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="airport" type="xs:string" fixed="XYU" />
        <xs:element name="updatedDate" type="xs:date" minOccurs="0" maxOccurs="1" />
        <xs:element name="updatedTime" type="xs:time" minOccurs="0" maxOccurs="1" />

        <!-- ARRIVALS -->
        <xs:element name="arrivals" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="arrival" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="flight" minOccurs="1" maxOccurs="1">
                      <xs:simpleType>
                        <xs:restriction base="xs:integer">
                          <xs:minInclusive value="1" />
                          <xs:maxInclusive value="9999" />
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="airline" minOccurs="1" maxOccurs="1">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:enumeration value="Air Canada" />
                          <xs:enumeration value="Air Transat" />
                          <xs:enumeration value="Sunwing" />
                          <xs:enumeration value="Swoop" />
                          <xs:enumeration value="WestJet" />
                          <xs:enumeration value="WestJet Encore" />
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="flightFrom" minOccurs="1" maxOccurs="1">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:enumeration value="Abbostsford" />
                          <xs:enumeration value="Calgary" />
                          <xs:enumeration value="Cancun" />
                          <xs:enumeration value="Cayo Santa Maria" />
                          <xs:enumeration value="Edmonton" />
                          <xs:enumeration value="Hamilton" />
                          <xs:enumeration value="Las Vegas" />
                          <xs:enumeration value="Montego Bay" />
                          <xs:enumeration value="Montreal" />
                          <xs:enumeration value="Orlando" />
                          <xs:enumeration value="Ottawa" />
                          <xs:enumeration value="Puerto Plata" />
                          <xs:enumeration value="Punta Cana" />
                          <xs:enumeration value="Sault Ste Marie" />
                          <xs:enumeration value="Toronto" />
                          <xs:enumeration value="Varadero" />
                          <xs:enumeration value="Winnipeg" />
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="schedTime" type="xs:time" minOccurs="1" maxOccurs="1" />
                    <xs:element name="actTime" type="xs:time" minOccurs="1" maxOccurs="1" />
                    <xs:element name="status" minOccurs="1" maxOccurs="1">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:enumeration value="Arrived" />
                          <xs:enumeration value="Cancelled" />
                          <xs:enumeration value="Diverted" />
                          <xs:enumeration value="Early" />
                          <xs:enumeration value="Late" />
                          <xs:enumeration value="On Time" />
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <!-- DEPARTURES -->
        <xs:element name="departures" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="departure">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="flight">
                      <xs:simpleType>
                        <xs:restriction base="xs:integer">
                          <xs:minInclusive value="1" />
                          <xs:maxInclusive value="9999" />
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="airline" minOccurs="1" maxOccurs="1">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:enumeration value="Air Canada" />
                          <xs:enumeration value="Air Transat" />
                          <xs:enumeration value="Sunwing" />
                          <xs:enumeration value="Swoop" />
                          <xs:enumeration value="WestJet" />
                          <xs:enumeration value="WestJet Encore" />
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="flightTo" minOccurs="1" maxOccurs="1">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:enumeration value="Abbostsford" />
                          <xs:enumeration value="Calgary" />
                          <xs:enumeration value="Cancun" />
                          <xs:enumeration value="Cayo Santa Maria" />
                          <xs:enumeration value="Edmonton" />
                          <xs:enumeration value="Hamilton" />
                          <xs:enumeration value="Las Vegas" />
                          <xs:enumeration value="Montego Bay" />
                          <xs:enumeration value="Montreal" />
                          <xs:enumeration value="Orlando" />
                          <xs:enumeration value="Ottawa" />
                          <xs:enumeration value="Puerto Plata" />
                          <xs:enumeration value="Punta Cana" />
                          <xs:enumeration value="Sault Ste Marie" />
                          <xs:enumeration value="Toronto" />
                          <xs:enumeration value="Varadero" />
                          <xs:enumeration value="Winnipeg" />
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="schedTime" type="xs:time" minOccurs="1" maxOccurs="1" />
                    <xs:element name="actTime" type="xs:time" minOccurs="1" maxOccurs="1" />
                    <xs:element name="status" minOccurs="1" maxOccurs="1">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:enumeration value="Cancelled" />
                          <xs:enumeration value="Departed" />
                          <xs:enumeration value="Delayed" />
                          <xs:enumeration value="On Time" />
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== cicerorfonseca/js-xml-xsd/flights.xml
<?xml version="1.0" encoding="utf-8" ?>
<flights xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="flights.xsd">
  <airport>XYU</airport>
  <updatedDate>2020-01-15</updatedDate>
  <updatedTime>15:27:00</updatedTime>
  <arrivals>
    <flight id="8659">
      <airline>Air Canada</airline>
      <flightFrom>Ottawa</flightFrom>
      <schedTime>13:50:09</schedTime>
      <actTime>13:50:09</actTime>
      <status>Arrived</status>
    </flight>
    <flight id="8649">
      <airline>Air Canada</airline>
      <flightFrom>Toronto</flightFrom>
      <schedTime>14:30:09</schedTime>
      <actTime>14:30:09</actTime>
      <status>Arrived</status>
    </flight>
    <flight id="735">
      <airline>Swoop</airline>
      <flightFrom>Orlando</flightFrom>
      <schedTime>14:11:09</schedTime>
      <actTime>14:11:09</actTime>
      <status>Arrived</status>
    </flight>
    <flight id="879">
      <airline>Air Transat</airline>
      <flightFrom>Punta Cana</flightFrom>
      <schedTime>16:15:09</schedTime>
      <actTime>16:15:09</actTime>
      <status>On Time</status>
    </flight>
    <flight id="736">
      <airline>Westjet</airline>
      <flightFrom>Calgary</flightFrom>
      <schedTime>22:16:09</schedTime>
      <actTime>22:16:09</actTime>
      <status>On Time</status>
    </flight>
  </arrivals>
  <departures>
    <flight id="8660">
      <airline>Air Canada</airline>
      <flightTo>Ottawa</flightTo>
      <schedTime>14:15:09</schedTime>
      <actTime>14:15:09</actTime>
      <status>Departed</status>
    </flight>
    <flight id="836">
      <airline>Swoop</airline>
      <flightTo>Orlando</flightTo>
      <schedTime>16:00:09</schedTime>
      <actTime>16:00:09</actTime>
      <status>Delayed</status>
    </flight>
    <flight id="846">
      <airline>Air Transat</airline>
      <flightTo>Cancun</flightTo>
      <schedTime>22:10:09</schedTime>
      <actTime>22:10:09</actTime>
      <status>On Time</status>
    </flight>
    <flight id="8660">
      <airline>Air Canada</airline>
      <flightTo>Ottawa</flightTo>
      <schedTime>14:15:09</schedTime>
      <actTime>14:15:09</actTime>
      <status>Departed</status>
    </flight>
    <flight id="374">
      <airline>Sunwing</airline>
      <flightTo>Varadero</flightTo>
      <schedTime>22:15:09</schedTime>
      <actTime>22:15:09</actTime>
      <status>On Time</status>
    </flight>
  </departures>
</flights>

=== cicerorfonseca/js-xml-xsd/flights-2.xml
<?xml version="1.0" encoding="utf-8" ?>
<flights xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="flights.xsd">
  <airport>XYU</airport>
  <updatedDate>2020-01-15</updatedDate>
  <updatedTime>15:27:00</updatedTime>
  <arrivals>
    <arrival>
      <flight>8564</flight>
      <airline>Air Canada</airline>
      <flightFrom>Ottawa</flightFrom>
      <schedTime>13:50:09</schedTime>
      <actTime>13:50:09</actTime>
      <status>Arrived</status>
    </arrival>
    <arrival>
      <flight>4512</flight>
      <airline>Air Canada</airline>
      <flightFrom>Toronto</flightFrom>
      <schedTime>14:30:09</schedTime>
      <actTime>14:30:09</actTime>
      <status>Late</status>
    </arrival>
    <arrival>
      <flight>9588</flight>
      <airline>Swoop</airline>
      <flightFrom>Orlando</flightFrom>
      <schedTime>14:11:09</schedTime>
      <actTime>14:11:09</actTime>
      <status>Early</status>
    </arrival>
    <arrival>
      <flight>251</flight>
      <airline>Air Transat</airline>
      <flightFrom>Punta Cana</flightFrom>
      <schedTime>16:15:09</schedTime>
      <actTime>16:15:09</actTime>
      <status>On Time</status>
    </arrival>
    <arrival>
      <flight>2514</flight>
      <airline>WestJet</airline>
      <flightFrom>Calgary</flightFrom>
      <schedTime>22:16:09</schedTime>
      <actTime>22:16:09</actTime>
      <status>On Time</status>
    </arrival>
    <arrival>
      <flight>3522</flight>
      <airline>WestJet</airline>
      <flightFrom>Varadero</flightFrom>
      <schedTime>22:16:09</schedTime>
      <actTime>22:16:09</actTime>
      <status>On Time</status>
    </arrival>
    <arrival>
      <flight>2251</flight>
      <airline>Swoop</airline>
      <flightFrom>Las Vegas</flightFrom>
      <schedTime>22:16:09</schedTime>
      <actTime>22:16:09</actTime>
      <status>On Time</status>
    </arrival>
    <arrival>
      <flight>3754</flight>
      <airline>WestJet Encore</airline>
      <flightFrom>Hamilton</flightFrom>
      <schedTime>22:16:09</schedTime>
      <actTime>22:16:09</actTime>
      <status>On Time</status>
    </arrival>
  </arrivals>
  <departures>
    <departure>
      <flight>7741</flight>
      <airline>Air Canada</airline>
      <flightTo>Ottawa</flightTo>
      <schedTime>14:15:09</schedTime>
      <actTime>14:15:09</actTime>
      <status>Departed</status>
    </departure>
    <departure>
      <flight>2254</flight>
      <airline>Swoop</airline>
      <flightTo>Orlando</flightTo>
      <schedTime>16:00:09</schedTime>
      <actTime>16:00:09</actTime>
      <status>Delayed</status>
    </departure>
    <departure>
      <flight>7844</flight>
      <airline>Air Transat</airline>
      <flightTo>Cancun</flightTo>
      <schedTime>22:10:09</schedTime>
      <actTime>22:10:09</actTime>
      <status>On Time</status>
    </departure>
    <departure>
      <flight>90</flight>
      <airline>Air Canada</airline>
      <flightTo>Ottawa</flightTo>
      <schedTime>14:15:09</schedTime>
      <actTime>14:15:09</actTime>
      <status>Departed</status>
    </departure>
    <departure>
      <flight>998</flight>
      <airline>Sunwing</airline>
      <flightTo>Varadero</flightTo>
      <schedTime>22:10:09</schedTime>
      <actTime>22:15:09</actTime>
      <status>On Time</status>
    </departure>
  </departures>
</flights>

=== cicerorfonseca/js-xml-xsd/flights-1.xml
<?xml version="1.0" encoding="utf-8" ?>
<flights xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="flights.xsd">
  <airport>XYU</airport>
  <updatedDate>2020-01-15</updatedDate>
  <updatedTime>15:27:00</updatedTime>
  <arrivals>
    <arrival>
      <flight>5564</flight>
      <airline>Swoop</airline>
      <flightFrom>Abbotsford</flightFrom>
      <schedTime>13:50:09</schedTime>
      <actTime>13:50:09</actTime>
      <status>Arrived</status>
    </arrival>
    <arrival>
      <flight>2343</flight>
      <airline>Air Canada</airline>
      <flightFrom>Orlando</flightFrom>
      <schedTime>14:30:09</schedTime>
      <actTime>14:30:09</actTime>
      <status>Late</status>
    </arrival>
    <arrival>
      <flight>2545</flight>
      <airline>Swoop</airline>
      <flightFrom>Winnipeg</flightFrom>
      <schedTime>14:11:09</schedTime>
      <actTime>14:11:09</actTime>
      <status>Early</status>
    </arrival>
    <arrival>
      <flight>3453</flight>
      <airline>Sunwing</airline>
      <flightFrom>Sault Ste Marie</flightFrom>
      <schedTime>16:15:09</schedTime>
      <actTime>16:15:09</actTime>
      <status>On Time</status>
    </arrival>
    <arrival>
      <flight>6767</flight>
      <airline>WestJet Encore</airline>
      <flightFrom>Cayo Santa Maria</flightFrom>
      <schedTime>22:16:09</schedTime>
      <actTime>22:16:09</actTime>
      <status>On Time</status>
    </arrival>
  </arrivals>
  <departures>
    <departure>
      <flight>548</flight>
      <airline>Sunwing</airline>
      <flightTo>Varadero</flightTo>
      <schedTime>22:15:09</schedTime>
      <actTime>22:15:09</actTime>
      <status>On Time</status>
    </departure>
    <departure>
      <flight>3343</flight>
      <airline>Swoop</airline>
      <flightTo>Orlando</flightTo>
      <schedTime>16:00:09</schedTime>
      <actTime>16:00:09</actTime>
      <status>Delayed</status>
    </departure>
    <departure>
      <flight>55</flight>
      <airline>Air Canada</airline>
      <flightTo>Ottawa</flightTo>
      <schedTime>14:15:09</schedTime>
      <actTime>14:15:09</actTime>
      <status>Departed</status>
    </departure>
    <departure>
      <flight>4433</flight>
      <airline>Air Transat</airline>
      <flightTo>Cancun</flightTo>
      <schedTime>22:10:09</schedTime>
      <actTime>22:10:09</actTime>
      <status>On Time</status>
    </departure>
    <departure>
      <flight>2232</flight>
      <airline>Air Canada</airline>
      <flightTo>Ottawa</flightTo>
      <schedTime>14:15:09</schedTime>
      <actTime>14:15:09</actTime>
      <status>Departed</status>
    </departure>
  </departures>
</flights>

=== cicerorfonseca/js-xml-xsd/flights-3.xml
<?xml version="1.0" encoding="utf-8" ?>
<flights xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="flights.xsd">
  <airport>XYU</airport>
  <updatedDate>2020-01-15</updatedDate>
  <updatedTime>15:27:00</updatedTime>
  <arrivals>
    <arrival>
      <flight>8564</flight>
      <airline>Air Canada</airline>
      <flightFrom>Ottawa</flightFrom>
      <schedTime>13:50:09</schedTime>
      <actTime>13:50:09</actTime>
      <status>Arrived</status>
    </arrival>
    <arrival>
      <flight>4512</flight>
      <airline>Air Canada</airline>
      <flightFrom>Toronto</flightFrom>
      <schedTime>14:30:09</schedTime>
      <!-- a.i. An invalid number of Arrivals fields -->
      <status>Late</status>
    </arrival>
    <arrival>
      <flight>9588</flight>
      <airline>Swoop</airline>
      <flightFrom>Orlando</flightFrom>
      <schedTime>14:11:09</schedTime>
      <actTime>14:11:09</actTime>
      <status>Early</status>
    </arrival>
    <arrival>
      <flight>251</flight>
      <!-- a.ii. An Arrival field containing an invalid number of Airline fields -->
      <airline>Air Transat</airline>
      <airline>United</airline>
      <flightFrom>Punta Cana</flightFrom>
      <schedTime>16:15:09</schedTime>
      <actTime>16:15:09</actTime>
      <status>On Time</status>
    </arrival>
    <arrival>
      <flight>2514</flight>
      <airline>WestJet</airline>
      <flightFrom>Calgary</flightFrom>
      <schedTime>22:16:09</schedTime>
      <actTime>22:16:09</actTime>
      <status>On Time</status>
    </arrival>
    <arrival>
      <flight>3522</flight>
      <airline>WestJet</airline>
      <flightFrom>Varadero</flightFrom>
      <schedTime>22:16:09</schedTime>
      <actTime>22:16:09</actTime>
      <status>On Time</status>
    </arrival>
    <arrival>
      <flight>2251</flight>
      <!-- b.i. An invalid Airline value for an Arrival -->
      <airline>United</airline>
      <flightFrom>Las Vegas</flightFrom>
      <schedTime>22:16:09</schedTime>
      <actTime>22:16:09</actTime>
      <status>On Time</status>
    </arrival>
    <arrival>
      <flight>3754</flight>
      <airline>WestJet Encore</airline>
      <!-- b.ii An invalid Arriving From value for an Arrival -->
      <flightFrom>Vancouver</flightFrom>
      <schedTime>22:16:09</schedTime>
      <actTime>22:16:09</actTime>
      <status>On Time</status>
    </arrival>
  </arrivals>
  <departures>
    <departure>
      <flight>7741</flight>
      <airline>Air Canada</airline>
      <flightTo>Ottawa</flightTo>
      <schedTime>14:15:09</schedTime>
      <actTime>14:15:09</actTime>
      <!-- b.iii. An invalid Status value for an Arrival -->
      <status>Arrived</status>
    </departure>
    <departure>
      <flight>2254</flight>
      <!-- a.iii. A Departure field containing an invalid number of Depart To fields -->
      <flightTo>Orlando</flightTo>
      <schedTime>16:00:09</schedTime>
      <actTime>16:00:09</actTime>
      <status>Delayed</status>
    </departure>
    <departure>
      <flight>7844</flight>
      <airline>Air Transat</airline>
      <!-- b.iv. An invalid Departing To value for a Departure -->
      <flightTo>Los Angeles</flightTo>
      <schedTime>22:10:09</schedTime>
      <actTime>22:10:09</actTime>
      <!-- a.iv. An element (anywhere) that is not defined in the schema -->
      <currTime>10:04:21</currTime>
      <status>On Time</status>
    </departure>
    <departure>
      <!-- a.v. An attribute (anywhere) that is not defined in the schema -->
      <flight id="90">90</flight>
      <airline>Air Canada</airline>
      <flightTo>Ottawa</flightTo>
      <schedTime>14:15:09</schedTime>
      <actTime>14:15:09</actTime>
      <status>Departed</status>
    </departure>
    <departure>
      <!-- b.v. An invalid Flight value for a Departure -->
      <flight>A998</flight>
      <airline>Sunwing</airline>
      <flightTo>Varadero</flightTo>
      <schedTime>22:10:09</schedTime>
      <!-- b.vi. An invalid Actual Time value for a Departure -->
      <actTime>22:15</actTime>
      <status>On Time</status>
    </departure>
  </departures>
</flights>
